# primer programa
print ('alvaro godinez rivero')
print ('cerrada acueducto obraje numero 8 ')
print ('sambartolome coatepec')
print (' huixquilucan edo mexico')
print ('cp 52770')
print ('')
print ('')
print ('')
print ('')
print ('')
print ('')
print ('                                                                 diego jacinto deciga')
print ('                                                              barrio buena vista sin #')
print ('                                                              naucalpan de juarez')

